name: deals_app
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dependencies:
  phlox_animations: any
  flutter_otp_text_field: ^1.0.1
  flutter_switch: ^0.3.2
  dots_indicator: ^2.1.0
  animated_bottom_navigation_bar: ^1.0.1
  cupertino_icons: ^1.0.2
  stacked:
  get_it:
  injectable:
  intl:
  intl_phone_field: ^3.1.0
  flutter_svg:
  stacked_services:
  dio:
  shared_preferences:
  flutter_masked_text2:
  cached_network_image:
  country_code_picker:
  flutter_rating_bar:
  expandable:
  expand_tap_area:
  emoji_picker_flutter: ^1.0.8
  page_transition:
  modal_bottom_sheet: ^2.0.1
  animations: ^2.0.2
  smooth_page_indicator: ^1.0.0+2
  curved_navigation_bar: ^1.0.1
  flutter_staggered_grid_view:
  country_picker: ^2.0.16
  image_picker: ^0.8.5+3
  reactive_forms: ^10.1.0
  counter: ^0.2.2
  custom_switch:
  country_dial_code: ^1.2.0
  firebase_core:
  firebase_auth:
  pinput:
  photo_view:
  google_maps_flutter: ^2.2.1
  timer_count_down: ^2.2.1
  slide_countdown: ^0.3.4
  share_plus:
  carousel_indicator: ^1.0.6
  location:





dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.4
  json_serializable: ^6.0.1

  #flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: PoppinsItalic
      fonts:
        - asset: assets/fonts/Poppins-Italic.ttf

    - family: playfairbold
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf

    - family: Poppinsitalic
      fonts:
        - asset: assets/fonts/Poppins-Italic.ttf

    - family: PoppinsSemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf


